#!/bin/bash

ROOT_DIR="$(cd $(dirname $0);pwd)/"
SITE_RESTART_ARG='restart'
SITE_RESTART="$1"
SITE_BIN='rackup'
SITE_HOST='127.0.0.1'
SITE_PORT_PERFIX='1664'
SITE_PORT_POSTFIX=
SITE_PID=
SITE_SERVER='thin'
SITE_ENV='production'
SITE_DIR=

for i in 0 2 4; do
	case $i in
		0 )
			SITE_DIR='www'
		;;
		2 )
			SITE_DIR='hackerspace'
		;;
		4 )
			SITE_DIR='gnu'
		;;
	esac
	SITE_PORT_POSTFIX=$i
	SITE_PID="$(echo $(ps ax | grep "$SITE_PORT_PERFIX$SITE_PORT_POSTFIX" | grep "$SITE_BIN") | cut -d\  -f1)"
	if [ "$SITE_RESTART" == "$SITE_RESTART_ARG" ]; then
		kill -9 "$SITE_PID"
		SITE_PID=''
	fi
	if [ "$SITE_PID" == "" ]; then
		cd "$ROOT_DIR$SITE_DIR"
		"$SITE_BIN" --host="$SITE_HOST" --port="$SITE_PORT_PERFIX$SITE_PORT_POSTFIX" --server="$SITE_SERVER" --env="$SITE_ENV" &
		cd "$ROOT_DIR"
	fi
done
