chepava:
  domain: by
  html: html5
  sites: gnu.by lvee.org hackerspace.by freediving.by spearfishing.by
  phone: +375 29 3179210;+375 33 3139210
  email: info
  foundation_year: 2010
  locale:
    default: en
    list: be ua ru lt fi se no en
